name: Bug Report
description: Report a bug in HelixScreen
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below so we can reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: HelixScreen Version
      description: "Run `helix-screen --version` or check Settings > About"
      placeholder: "e.g. v0.9.10"
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware Platform
      description: What hardware is HelixScreen running on?
      options:
        - Raspberry Pi 5
        - Raspberry Pi 4
        - Raspberry Pi 3
        - BTT Pi v2
        - BTT CB1
        - Other (describe below)
    validations:
      required: true

  - type: input
    id: screen
    attributes:
      label: Screen / Display
      description: "Screen model and resolution (e.g. BTT HDMI5, Waveshare 7inch, etc.)"
      placeholder: "e.g. BTT HDMI5 (800x480)"
    validations:
      required: true

  - type: dropdown
    id: printer
    attributes:
      label: Printer Model
      description: "Select your printer. Choose 'Other' if yours is not listed."
      multiple: true
      options:
        # Anycubic
        - Anycubic Chiron
        - Anycubic i3 Mega
        - Anycubic Kobra
        - Anycubic Kobra 2
        - Anycubic Kobra 2 Max
        - Anycubic Kobra 3
        - Anycubic Kobra S1
        - Anycubic Kobra S1 Max
        - Anycubic Vyper
        # Bambu Lab
        - Bambu Lab (Klipper)
        # Creality
        - Creality CR-10
        - Creality Ender 3
        - Creality Ender 5
        - Creality Ender 5 Max
        - Creality Ender-3 S1
        - Creality Ender-3 V3
        - Creality Ender-3 V3 KE
        - Creality K1
        - Creality K1 Max
        - Creality K1 SE
        - Creality K1C
        - Creality K2 Plus
        # Doron
        - Doron Velta
        # Elegoo
        - Elegoo Centauri Carbon
        - Elegoo Neptune 4
        - Elegoo Neptune 4 Max
        - Elegoo Neptune 4 Plus
        - Elegoo Neptune 4 Pro
        # FlashForge
        - FlashForge Adventurer 5M
        - FlashForge Adventurer 5M Pro
        - FlashForge Adventurer 5X
        # FLSUN
        - FLSUN Delta
        - FLSUN Super Racer
        - FLSUN V400
        # Geralkom
        - Geralkom X400 HT
        - Geralkom X500 HT
        # Infimech
        - Infimech TX
        # Kingroon
        - Kingroon KLP1
        - Kingroon KP3S Pro V2
        - Kingroon KP5L
        # Lemontron
        - Lemontron
        # PFA / Positron3D
        - PFA Micron
        - PrusaWire (Positron3D)
        # Prusa Research
        - Prusa MK4
        # Qidi
        - Qidi Plus 4
        - Qidi Q1 Pro
        - Qidi Q2
        - Qidi X-Max 3
        - Qidi X-Plus 3
        # RatRig
        - RatRig V-Core 3
        - RatRig V-Minion
        # Snapmaker
        - Snapmaker U1
        # Sovol
        - Sovol SV06
        - Sovol SV06 Plus
        - Sovol SV07
        - Sovol SV08
        - Sovol SV08 Max
        - Sovol Zero
        # Voron
        - Voron 0.2
        - Voron 2.4
        - Voron Switchwire
        - Voron Trident
        # Other
        - Other (describe below)
    validations:
      required: true

  - type: input
    id: printer_other
    attributes:
      label: Other Printer (if not listed above)
      description: "If you selected 'Other', describe your printer and Klipper/Moonraker version"
      placeholder: "e.g. Custom CoreXY, Klipper v0.12.x, Moonraker v0.9.x"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: "Describe the issue clearly..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Go to '...'
        2. Tap on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Run with `helix-screen -vv` and paste relevant output. Wrap in a code block."
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots. Press 'S' in the UI to capture."
    validations:
      required: false
