name: Feature Request
description: Suggest a new feature or improvement for HelixScreen
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for HelixScreen? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: "What problem does this solve? What's frustrating or missing?"
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: "How would you like this to work?"
      placeholder: "It would be great if..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: "Have you tried any workarounds or considered other approaches?"
    validations:
      required: false

  - type: dropdown
    id: printer
    attributes:
      label: Printer Model
      description: "If relevant to the request, select your printer."
      multiple: true
      options:
        # Anycubic
        - Anycubic Chiron
        - Anycubic i3 Mega
        - Anycubic Kobra
        - Anycubic Kobra 2
        - Anycubic Kobra 2 Max
        - Anycubic Kobra 3
        - Anycubic Kobra S1
        - Anycubic Kobra S1 Max
        - Anycubic Vyper
        # Bambu Lab
        - Bambu Lab (Klipper)
        # Creality
        - Creality CR-10
        - Creality Ender 3
        - Creality Ender 5
        - Creality Ender 5 Max
        - Creality Ender-3 S1
        - Creality Ender-3 V3
        - Creality Ender-3 V3 KE
        - Creality K1
        - Creality K1 Max
        - Creality K1 SE
        - Creality K1C
        - Creality K2 Plus
        # Doron
        - Doron Velta
        # Elegoo
        - Elegoo Centauri Carbon
        - Elegoo Neptune 4
        - Elegoo Neptune 4 Max
        - Elegoo Neptune 4 Plus
        - Elegoo Neptune 4 Pro
        # FlashForge
        - FlashForge Adventurer 5M
        - FlashForge Adventurer 5M Pro
        - FlashForge Adventurer 5X
        # FLSUN
        - FLSUN Delta
        - FLSUN Super Racer
        - FLSUN V400
        # Geralkom
        - Geralkom X400 HT
        - Geralkom X500 HT
        # Infimech
        - Infimech TX
        # Kingroon
        - Kingroon KLP1
        - Kingroon KP3S Pro V2
        - Kingroon KP5L
        # Lemontron
        - Lemontron
        # PFA / Positron3D
        - PFA Micron
        - PrusaWire (Positron3D)
        # Prusa Research
        - Prusa MK4
        # Qidi
        - Qidi Plus 4
        - Qidi Q1 Pro
        - Qidi Q2
        - Qidi X-Max 3
        - Qidi X-Plus 3
        # RatRig
        - RatRig V-Core 3
        - RatRig V-Minion
        # Snapmaker
        - Snapmaker U1
        # Sovol
        - Sovol SV06
        - Sovol SV06 Plus
        - Sovol SV07
        - Sovol SV08
        - Sovol SV08 Max
        - Sovol Zero
        # Voron
        - Voron 0.2
        - Voron 2.4
        - Voron Switchwire
        - Voron Trident
        # Other
        - Other (describe below)
    validations:
      required: false

  - type: input
    id: printer_other
    attributes:
      label: Other Printer / Hardware Setup (if not listed above)
      description: "If you selected 'Other' or want to add hardware details (Pi model, screen, etc.)"
      placeholder: "e.g. Custom CoreXY, Pi 5, BTT HDMI5"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Mockups
      description: "If you have any visuals to illustrate the idea, attach them here."
    validations:
      required: false
