#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Generate build/generated/contributors.h from git history

set -euo pipefail

OUTDIR="build/generated"
OUTFILE="$OUTDIR/contributors.h"
TMPFILE="$(mktemp)"

trap 'rm -f "$TMPFILE"' EXIT

mkdir -p "$OUTDIR"

# Get unique contributor names, excluding bots and invalid entries
contributors=$(git log --format='%aN' | sort -u \
    | grep -ivE 'bot\b|\[bot\]|dependabot|github-actions|claude' \
    | awk 'length >= 2' || true)

# Generate the header into a temp file
{
    echo "// SPDX-License-Identifier: GPL-3.0-or-later"
    echo "// Auto-generated by gen-contributors.sh — do not edit"
    echo "#pragma once"
    echo ""
    echo "inline constexpr const char* kContributors[] = {"
    while IFS= read -r name; do
        [ -z "$name" ] && continue
        # Escape any double quotes in names
        escaped=$(printf '%s' "$name" | sed 's/"/\\"/g')
        echo "    \"$escaped\","
    done <<< "$contributors"
    echo "};"
    echo ""
    echo "inline constexpr int kContributorCount = sizeof(kContributors) / sizeof(kContributors[0]);"
} > "$TMPFILE"

# Only update if content changed
if [ -f "$OUTFILE" ] && diff -q "$TMPFILE" "$OUTFILE" >/dev/null 2>&1; then
    exit 0
fi

cp "$TMPFILE" "$OUTFILE"
echo "Generated $OUTFILE"
